version: '3'
services:
  frontend_server:
    image: tlsrhkdcjs12/night-front:latest
    restart: "always"
    volumes:
        - /etc/letsencrypt:/etc/letsencrypt
        - /home/elice/nginx.conf:/etc/nginx/conf.d/nginx.conf
        - /home/elice/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
        - 80:80
        - 443:443
  backend_server:
    image: tlsrhkdcjs12/night-back:latest
    restart: "always"
    ports:
      - 5001:5001
  ai_server:
    image: tlsrhkdcjs12/night-ai:latest
    restart: "always"
    ports:
      - 5000:5000
